import ex from "./components/ex.js";
import slider from "./components/slider";
import menu from "./components/menu";
import header from "./components/header";
import advantage from "./components/advantageList";
import diseases from "./components/diseases";
import formInfo from  "./components/formInfo";
import  formBlock from  "./components/formBlock";
import  reasons from  "./components/reasons";